service:
  flush: 1
  parsers_file: "${FLUENTBIT_HOME}/conf/parsers.conf"

pipeline:
  inputs:
    - name: tail
      tag: nginx-feed
      path: ./nginx.json.log
      read_from_head: true
      parser: json

  filters:
    - name: checklist
      match: "*"
      file: ./fluentbit/ip-checklist.data
      lookup_key: remote_ip
      ignore_case: false
      mode: partial
      record known_origin: yes
      print_query_time: true

  outputs:
    - name: stdout
      match: "*"
