service:
  flush: 1

pipeline:
  inputs:
    - name: dummy
      tag: dummy1
      dummy: '{   "time": "12/May/2023:08:05:52 +0000",   "remote_ip": "10.4.72.163",   "remoteuser": "-",   "request": {     "verb": "GET",     "path": " /downloads/product_2",     "protocol": "HTTP",     "version": "1.1"   },   "response": 304}'

    - name: dummy
      tag: dummy2
      dummy: '{   "time": "12/June/2023:08:05:52 +0000",   "remote_ip": "10.4.72.163",   "remote_user": "-",   "request": {     "verb": "GET",     "path": " /downloads/product_2",     "protocol": "HTTP",     "version": "1.1"   },   "response": 304, "another_root_element" : "horrah", "why" : ["just"," so", " the counter"," varies"]}'

  filters:
    - name: lua
      match: "*"
      script: ./attribute-types.lua
      call: cb_displayDataAndTypes
      time_as_table: true
      #protected_mode: true

  outputs:
    - name: null
      match: "*"
