service:
  flush: 1
  daemon: off
  log_level: info

pipeline:
  inputs:
    - name: dummy
      copies: 5
      rate: 1
      dummy: { "message": "dummy" }
      tag: throttle_demo

  filters:
    - name: throttle
      match: "*"
      rate: 2
      window: 3
      interval: 2s
      print_status: true

  outputs:
    - name: stdout
      match: "*"
