service:
  flush: 1

pipeline:
  inputs:
    - name: tail
      path: ./basic-file.txt
      read_from_head: true
      exit_on_eof: true
      tag: basic-file

  outputs:
    - name: stdout
      match: "*"
