env:
  flush_interval: 1

service:
  flush: ${flush_interval}
  log_level: info

pipeline:
  inputs:
    - name: disk
      interval_sec: 5
      tag: book_vm_disk

    - name: cpu
      interval_sec: 5
      tag: book_vm_cpu

    - name: mem
      interval_sec: 5
      tag: book_vm_memory

    - name: netif
      interface: eth0
      interval_sec: 5
      tag: book_vm_network

  #
  # Warning - upto Fluent Bit 3.0.6 - these input plugins are unavailable in a standard MacOS build
  #

  outputs:
    - name: stdout
      match: "*"
