env:
  flush_interval: 2

service:
  flush: ${flush_interval}
  log_level: info
  #logLevel: info

pipeline:
  inputs:
    - name: dummy
      dummy: '{ "hello": "my world" }'
      tag: dummy1

  outputs:
    - name: stdout
      match: "*"
