env:
  flush_interval: 1

service:
  flush: ${flush_interval}
  log_level: info

pipeline:
  inputs:
    - name: dumm
      dummy: '{ "hello": "my world" }'
      tag: dummy1

  outputs:
    - name: stdt
      match: "*"
