service:
  log_level: info
  http_server: on
  flush: 1

pipeline:
  inputs:
    - name: node_exporter_metrics
      tag: flb-metrics
      scrape_interval: 10
      processors:
        metrics:
          - name: metrics_selector
            action: include
            metric_name: /^node_cpu*/
  outputs:
    - name: stdout
      match: "*"
