service:
  log_level: debug
  http_server: on
  flush: 1

pipeline:
  inputs:
    - name: opentelemetry
      listen: 0.0.0.0
      port: 4317
      tag_key: "blah"
      processors:
        traces:
          - name: content_modifier
            action: insert
            context: span_attributes
            key: "BIGKey"
            value: "Modified"
  outputs:
    - name: stdout
      match: "*"
