service:
  flush: 1
  log_level: warn
  scheduler.base: 1
  scheduler.cap: 15

pipeline:
  inputs:
    - name: http
      tag: http
      listen: 0.0.0.0
      port: 9881
      successful_response_code: 201
      success_header: x-fluent-bit received

  outputs:
    - name: forward
      match: "*"
      host: 0.0.0.0
      port: 9980
      retry_limit: 6
