service:
  flush: 1
  log_level: debug
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020
  storage.metrics: on

pipeline:
  inputs:
    - name: cpu
      tag: book_vm_cpu
      interval_nsec: 10

    - name: netif
      tag: book_vm_network
      interval_nsec: 10
      interface: eth0

    - name: mem
      tag: book_vm_memory
      interval_nsec: 10

  outputs:
    - name: null
      match: "*"
