service:
  flush: 1
  log_level: error

pipeline:
  inputs:
    - name: http
      tag: http-in
      listen: 0.0.0.0
      port: 9881

  outputs:
    - name: stdout
      match: "*"
      json_date_key: received-date
      json_date_format: iso8601
      format: json_stream
