service:
  flush: 5
  daemon: Off
  log_level: info
  parsers_file: parsers.conf
  plugins_file: plugins.conf
  HTTP_server: Off
  HTTP_listen: 0.0.0.0
  HTTP_port: 2020

pipeline:
  inputs:
    - name: in_gdb
      tag: db1
      db_host: 127.0.0.1
      # you may need to reconfigure this host address to point to your DB server
      db_port: 3306
      db_user: demo
      db_password: demo
      ordering_col: a_key
      table_name: pluginsrc
      db_name: demo
      db_type: mysql
      pk: a_key
      delete: "false"
      query_cols: a_key, a_string

  outputs:
    - name: stdout
      match: "*"
