service:
  flush: 5
  daemon: Off
  log_level: info
  plugins_file: plugins.conf

pipeline:
  inputs:
    - name: in_gdb
      tag: db1
      db_host: 127.0.0.1
      # you may need to reconfigure this host address to point to your DB server
      db_port: 3306
      db_user: demo
      db_password: demo
      ordering_col: a_key
      table_name: pluginsrc
      db_name: demo
      db_type: mysql
      pk: a_key
      delete: false
      query_cols: a_key, a_string

  outputs:
    - name: out_gdb
      match: "*"
      plugin_instance_id: instance_1
      db_host: 127.0.0.1
      # you may need to reconfigure this host address to point to your DB server
      db_port: 3306
      db_user: demo
      db_password: demo
      ordering_col: a_key
      table_name: pluginsrc
      db_name: demo
      db_type: mysql
      pk: a_key
      log_level: debug

    - name: out_gdb
      match: "*"
      plugin_instance_id: instance_2
      db_host: 127.0.0.1
      # you may need to reconfigure this host address to point to your DB server
      db_port: 3306
      db_user: demo
      db_password: demo
      ordering_col: a_key
      table_name: pluginsrc
      db_name: demo
      db_type: mysql
      pk: a_key
      log_level: debug
