service:
  flush: 1
  parsers_file:
    - ./fluentbit/parsers2.conf
    - "${FLUENTBIT_HOME}/conf/parsers.conf"

pipeline:
  inputs:
    - name: tail
      path: ./nginx-log
      read_from_head: true
      tag: nginx-feed

  filters:
    - name: parser
      match: "*"
      key_name: log
      parser: nginx
      preserve_key: true
      reserve_data: true

    - name: parser
      match: "*"
      key_name: log
      parser: myNginxSubset
      preserve_key: true
      reserve_data: true

    - name: parser
      match: "*"
      key_name: IPv4
      parser: myNginxOctet1
      preserve_key: true
      reserve_data: true

  outputs:
    - name: stdout
      match: "*"
